
import React, { useRef } from 'react';
import { Target, Zap, Shield, TrendingUp, AlertTriangle, Share2, FileText, Globe, Award, MessageCircle, Download, Printer } from 'lucide-react';
import { ResearchOutput } from '../types';

interface Props {
  data: ResearchOutput;
  query: string;
}

const BottomUpReport: React.FC<Props> = ({ data, query }) => {
  const intel = data.alphaIntel;
  const reportRef = useRef<HTMLDivElement>(null);

  const brandingFooter = "Generate By SAVAN KOTAK | Powered By MCARE Financial Service | Generated By Deep AI Intelligence";
  const disclaimerText = "Disclaimer : This report is generated with the help of AI using publicly available online data and may contain errors or outdated information. It is for educational purposes only and does not constitute investment, tax, legal, or other professional advice or a recommendation to buy or sell any security. Always do your own research and consult qualified advisors before making financial decisions; neither the author nor the AI provider is responsible for any loss arising from use of this report";

  const handleWhatsAppShare = (e: React.MouseEvent) => {
    e.preventDefault();
    if (!data || !data.text) return;
    
    const header = `*--- MCARE ALPHA RESEARCH DISPATCH ---*`;
    const title = `*ENTITY:* ${query.toUpperCase()}`;
    const dateLine = `*AUDIT DATE:* ${new Date().toLocaleDateString()}`;
    
    const allWords = data.text.split(/\s+/);
    const wordLimit = 800; 
    let compressedText = allWords.slice(0, wordLimit).join(' ');
    
    if (allWords.length > wordLimit) {
      compressedText += "\n\n... [Full Analysis available in Terminal]";
    }

    const fullMessage = `${header}\n${title}\n${dateLine}\n\n${compressedText}\n\n*BRANDING:*\n${brandingFooter}\n\n*DISCLAIMER:*\n_${disclaimerText}_`;
    
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(fullMessage)}`;
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
  };

  const handleGeneratePDF = () => {
    window.print();
  };

  const handleExportWord = () => {
    if (!data || !data.text) return;

    const contentHtml = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset="utf-8">
        <title>MCARE RESEARCH REPORT</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #000; }
          .header { border-bottom: 4px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { font-size: 24pt; text-transform: uppercase; margin: 0; font-weight: 900; }
          .header p { font-size: 10pt; text-transform: uppercase; margin: 5px 0; letter-spacing: 2px; }
          .meta { font-size: 11pt; font-weight: bold; text-transform: uppercase; margin-top: 20px; }
          .report-body { line-height: 1.6; font-size: 11pt; margin-top: 30px; text-align: justify; }
          .report-body h2 { font-size: 14pt; border-left: 5px solid #3b82f6; padding-left: 10px; margin-top: 25px; text-transform: uppercase; }
          .footer-section { border-top: 1px solid #000; margin-top: 50px; padding-top: 20px; }
          .branding { text-align: center; font-weight: bold; font-size: 10pt; text-transform: uppercase; margin-bottom: 15px; }
          .disclaimer { font-size: 9pt; color: #333; font-style: italic; border: 1px solid #ccc; padding: 10px; background: #f9f9f9; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>MCARE Financial Service</h1>
          <p>Institutional Alpha Intelligence Hub</p>
          <div class="meta">
            Audit Registry : ${new Date().toLocaleDateString()} <br>
            Company Name : ${query.toUpperCase()}
          </div>
        </div>
        
        <div class="report-body">
          ${data.text.split('\n').map(line => line.trim().startsWith('###') ? `<h2>${line.replace('###', '').trim()}</h2>` : `<p>${line}</p>`).join('')}
        </div>

        <div class="footer-section">
          <div class="branding">${brandingFooter}</div>
          <div class="disclaimer">
            <strong>Standard Disclaimer:</strong><br>
            ${disclaimerText}
          </div>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', contentHtml], {
      type: 'application/msword'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `MCARE_Report_${query.toUpperCase()}_${new Date().toISOString().split('T')[0]}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!intel) return null;

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-6 duration-700" id="alpha-report-root">
      {/* Print-Only Header */}
      <div className="print-only print-header">
        <div className="flex flex-col w-full border-b-4 border-black pb-6">
          <h1 className="text-4xl font-black uppercase m-0 leading-none">MCARE Financial Service</h1>
          <p className="text-sm font-bold tracking-[0.3em] uppercase text-slate-800 mt-2">Institutional Alpha Intelligence Hub</p>
          <div className="mt-8 flex flex-col gap-1 text-xs font-bold uppercase tracking-wider">
            <span>Audit Registry : {new Date().toLocaleDateString()}</span>
            <span className="text-lg">Company Name : {query.toUpperCase()}</span>
          </div>
        </div>
      </div>

      {/* Metrics Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 no-print">
        <div className="bg-[#12141c] border border-indigo-500/20 p-6 rounded-3xl shadow-xl flex flex-col justify-between">
          <div>
            <Award className="w-8 h-8 text-indigo-500 mb-4" />
            <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1">Moat Rating</h4>
            <div className="text-4xl font-black text-white font-mono">{intel.moatScore}%</div>
          </div>
          <p className="text-[9px] text-emerald-400 font-black uppercase tracking-widest mt-4">Wide Economic Barrier</p>
        </div>

        <div className="bg-[#12141c] border border-white/5 p-6 rounded-3xl shadow-xl">
          <AlertTriangle className={`w-8 h-8 mb-4 ${intel.riskRating === 'HIGH' ? 'text-rose-500' : 'text-amber-500'}`} />
          <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1">Risk Profile</h4>
          <div className="text-2xl font-black text-white">{intel.riskRating}</div>
          <div className="mt-2 w-full h-1 bg-white/5 rounded-full overflow-hidden">
             <div className="h-full bg-amber-500 w-1/2" />
          </div>
        </div>

        <div className="bg-indigo-600 p-6 rounded-3xl shadow-2xl shadow-indigo-600/20 flex flex-col justify-center items-center text-center">
          <TrendingUp className="w-8 h-8 text-white/50 mb-3" />
          <h4 className="text-[10px] font-black text-white/60 uppercase tracking-widest mb-1">Impact Velocity</h4>
          <div className="text-xl font-black text-white uppercase tracking-tighter">High Potential</div>
        </div>
      </div>

      {/* Main Report Body */}
      <div ref={reportRef} className="bg-[#0f1117] border border-white/5 p-8 lg:p-12 rounded-[2.5rem] relative shadow-2xl overflow-hidden print:bg-white print:border-none print:shadow-none print:p-0 print:m-0">
        <div className="absolute top-0 right-0 p-8 opacity-5 no-print">
          <FileText className="w-32 h-32 text-indigo-500" />
        </div>

        <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-12 border-b border-white/5 pb-8 gap-6 no-print">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-indigo-600/10 rounded-2xl border border-indigo-500/20">
              <TrendingUp className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
              <h2 className="text-2xl font-black text-white uppercase tracking-tighter">MCARE Alpha Report</h2>
              <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.4em]">ENTITY: {query.toUpperCase()}</p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={handleGeneratePDF}
              className="flex items-center gap-2 px-4 py-2 bg-white hover:bg-slate-100 text-black rounded-xl text-[10px] font-black transition-all shadow-xl active:scale-95 uppercase tracking-widest border border-slate-200"
            >
              <Printer className="w-4 h-4" />
              PDF
            </button>
            <button 
              onClick={handleExportWord}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-[10px] font-black transition-all shadow-xl shadow-blue-600/20 active:scale-95 uppercase tracking-widest"
            >
              <FileText className="w-4 h-4" />
              Word
            </button>
            <button 
              onClick={handleWhatsAppShare}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-[10px] font-black transition-all shadow-xl shadow-emerald-600/20 active:scale-95 uppercase tracking-widest"
            >
              <MessageCircle className="w-4 h-4" />
              WhatsApp
            </button>
          </div>
        </div>

        <div className="prose prose-invert prose-sm max-w-none text-slate-300 leading-relaxed font-medium mb-12 print:text-black print:prose-black print:max-w-full">
          {data.text.split('\n').map((line, i) => {
            if (line.trim().startsWith('###')) {
              return <h3 key={i} className="text-white font-black uppercase tracking-widest mt-12 mb-6 text-sm border-l-4 border-indigo-600 pl-4 print:text-black print:border-black">{line.replace('###', '').trim()}</h3>;
            }
            if (line.trim() === '') return <br key={i} />;
            return <p key={i} className="mb-4">{line}</p>;
          })}
        </div>

        <div className="border-t border-white/10 pt-10 print:border-black">
          <h4 className="text-[11px] font-black text-white uppercase tracking-widest mb-4 print:text-black">Standard Disclaimer</h4>
          <p className="text-[10px] text-slate-500 italic leading-relaxed print:text-black font-medium">
            {disclaimerText}
          </p>
        </div>

        {/* Footer Branding */}
        <div className="mt-12 text-center text-[10px] font-black uppercase tracking-widest text-slate-600 border-t border-white/5 pt-6 print:text-black print:border-black">
          {brandingFooter}
        </div>

        <div className="print-footer no-print print-only">
          {brandingFooter}
        </div>
      </div>
    </div>
  );
};

export default BottomUpReport;