
import React from 'react';
import { Newspaper, TrendingUp, Globe, Zap, ExternalLink, Share2, MessageCircle } from 'lucide-react';
import { ResearchOutput } from '../types';

interface Props {
  brief: ResearchOutput | null;
  loading: boolean;
}

const MarketBrief: React.FC<Props> = ({ brief, loading }) => {
  const handleWhatsAppShare = (e: React.MouseEvent) => {
    e.preventDefault();
    if (!brief) return;
    
    const branding = "Generated by Savan Kotak | Powered by AI Intelligence";
    const disclaimer = "Disclaimer: Educational purposes only. Consult a financial advisor.";
    
    // Safety limit for snippet
    const snippet = brief.text.length > 1000 
      ? brief.text.substring(0, 1000).trim() + "..." 
      : brief.text;
    
    const message = `*SAVAN ALPHA: MORNING BRIEF*\n\n${snippet}\n\n*${branding}*\n\n_${disclaimer}_`;
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
  };

  if (loading) {
    return (
      <div className="bg-[#12141c] border border-[#262b3d] rounded-2xl p-8 flex flex-col items-center justify-center animate-pulse">
        <Newspaper className="w-12 h-12 text-indigo-500/20 mb-4" />
        <p className="text-slate-500 text-xs font-black uppercase tracking-widest">Synthesizing Morning Brief...</p>
      </div>
    );
  }

  return (
    <div className="bg-[#12141c] border border-[#262b3d] rounded-2xl overflow-hidden shadow-2xl">
      <div className="bg-[#1a1d29] px-6 py-4 border-b border-[#262b3d] flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Zap className="w-4 h-4 text-amber-400" />
          <h3 className="text-sm font-black text-white uppercase tracking-widest">Morning Alpha Brief</h3>
        </div>
        <div className="flex items-center gap-4">
           {brief && (
             <button 
               onClick={handleWhatsAppShare}
               className="flex items-center gap-2 bg-emerald-600/10 hover:bg-emerald-600/20 border border-emerald-500/20 px-3 py-1.5 rounded-full text-[10px] font-black text-emerald-400 transition-all uppercase tracking-tighter"
             >
               <MessageCircle className="w-3.5 h-3.5" />
               Share
             </button>
           )}
           <div className="flex items-center gap-2">
              <Globe className="w-3 h-3 text-indigo-400" />
              <span className="text-[10px] font-black text-indigo-400 uppercase">Global Cues</span>
           </div>
        </div>
      </div>
      
      <div className="p-6">
        {brief ? (
          <div className="space-y-6">
            <div className="prose prose-invert prose-sm max-w-none text-slate-300 font-medium leading-relaxed">
              {brief.text.split('\n').map((line, i) => (
                <p key={i} className="mb-2">{line}</p>
              ))}
            </div>
            
            {brief.sources.length > 0 && (
              <div className="pt-4 border-t border-[#262b3d]">
                <h4 className="text-[10px] font-black text-slate-500 uppercase mb-3">Verified Sources</h4>
                <div className="flex flex-wrap gap-2">
                  {brief.sources.slice(0, 3).map((s, i) => (
                    <a key={i} href={s.uri} target="_blank" className="flex items-center gap-2 bg-[#1a1d29] px-3 py-1.5 rounded-lg text-[10px] font-bold text-indigo-400 hover:text-white transition-colors">
                      {s.title} <ExternalLink className="w-2.5 h-2.5" />
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="text-center py-8">
            <TrendingUp className="w-12 h-12 text-slate-800 mx-auto mb-4" />
            <p className="text-slate-600 text-xs font-bold uppercase">Initialize morning briefing to begin research session.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default MarketBrief;
